Reworking of lists, etc (#60)
n order to support more natural list ops, I made the list implementation use a read/write lock, and relegated the lock-free array to the cobwebs. I fixed some little bugs around it all.

I also refactored the collection algorithm to be breadth first instead of depth first, and re-arranged most structs to put pointers first, then 64-bit ints, since there were definitely some unaligned pointer issues w/ GCC (which could possibly persist in the stack layout, but hopefully not).

Debug builds now automatically run asan and ubsan; currently on my machine, there is one UB error, but as far as I can tell it is some false positive. What it's saying doesn't seem to map to the code even a little bit.

Particularly:

It's complaining about a bad boolean load.
The boolean is local, and explicitly initialized with bool flush = false.
The debugger agrees that the keyword argument that could modifies the address does not, and that, indeed, nothing modifies it on the call in question, when breaking on the function (verified w/ a hardware watchpoint).
This happens one and only one time across thousands and thousands of similar calls. But always in the same place.
HOWEVER, when the stack frame is entered, the value is somehow true already.
When I rearrange the declarations in the stack frame, I get the thing still.
I think there's a good chance there's just some weird ASAN byte being written, and it's just some weird false. But maybe not. Either way, I didn't chase it for long, and don't plan to (spent more time describing it than working it).

Also, along the way:
* Did all the con4m renaming I've been putting off, including the variadic macros, which I've mostly eliminated.
* String hash function has been customized to work right w/ u32, empty strings, etc. Also, fill in the list when there's an error in the lex phase.
* More basic tests
* Fix the comma in int formatting; the logic was sound but the counter never incremented.
* Made it so that uncaught exceptions will actually print (added a default handler for uncaught exceptions)
* Provide a value for TERM to the runner.
* Added a hard wrap to the terminal width for c4m_print(), which is currently on by default.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -44,7 +44,8 @@ function meson_build {
             rm -rf ${1}
         fi
         log Creating meson target ${1}
-        meson setup ${1}
+        log meson setup ${@}
+        meson setup ${@}
     fi
     cd ${1}
 
@@ -120,6 +121,10 @@ function debug_it {
     DEBUGGER=${DEBUGGER:-$(which lldb)}
     cd debug
     log "Running debugger:v${DEBUGGER}"
+    echo
+    echo $(color RED 'Recommended environment variables:')
+    echo $(color CYAN 'export ASAN_OPTIONS=halt_on_error=0')
+    echo $(color CYAN 'export UBSAN_OPTIONS=print_stacktrace=1;halt_on_error=0')
     ${DEBUGGER} ./c4test
     cd ..
 
@@ -136,7 +141,7 @@ function libcon4m_run_tests {
     ./c4test $@
     EXIT=$?
     log "Exit status: ${EXIT}"
-    if [[ ${EXIT} -gt 0 ]] && [[${EXIT} -lt 128 ]] && [[ $@ == "" ]]  ; then
+    if [[ ${EXIT} -gt 0 ]] && [[ ${EXIT} -lt 128 ]] && [[ $@ == "" ]]  ; then
         log "Test runner crashed; rerunning tests individually to isolate."
         HERE=`pwd`
         cd ../tests
@@ -151,7 +156,7 @@ function libcon4m_run_tests {
                 echo
             fi
         done
-        exit -1
+        exit 127
     fi
     cd ..
 }
@@ -176,13 +181,24 @@ fi
 case $1 in
     clean)   libcon4m_dev_clean
              ;;
-    build)   meson_build build
+    build)   meson_build build --buildtype=plain
              ;;
-    debug)   debug_it
+    debug)   meson_build debug --buildtype=debug
+             debug_it
              ;;
     release) meson_build release --buildtype=release
              ;;
-    run)     libcon4m_run_tests $@
+    run)
+             set -e
+             libcon4m_run_tests $@
+             CODE=$?
+             if [[ $CODE -eq 0 ]] ; then
+                 log "CI/CD tests passed."
+             else
+                 log "CI/CD Tests FAILED."
+                 exit $CODE
+             fi
+
              ;;
     hash)    meson_hatrack hash
              ;;
