Housekeeping: code reorg and build process redo (#87)
- Reorganized the con4m src and include directories to make them more sane (haven't gone IWYU though, just more sane on the file system)
- Retool the build process; the dev command now lets you switch profiles with 'dev profile' and passes any additional config options to meson. There are now MORE config options, including 'show_preprocessor_config' which dumps emits compiler warnings with the values of preproc config info.
- Fix the issue w/ CON4M_ROOT being necessary to run tests.
- Remove unnecessary alignment specs
- Remove depreciation warning.

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-export LIBRARY_PATH=${HOME}/.local/c0/libs/
+C4M_DEV_CFG="--buildtype=debug -Duse_memcheck=on -Ddev_mode=true"
+C4M_RELEASE_CFG="--buildtype=release"
+C4M_DEBUG_EXTRA="-Duse_ubsan=enabled -Duse_asan=enabled -Dshow_preprocessor_config=enabled"
+C4M_TEST_CFG=${C4M_DEV_CFG}
+
+
+C4M_MESON_STATE_FILE=.meson_last
+C4M_TEST_EXE=c4test
 
 function color {
     case $1 in
@@ -32,49 +39,15 @@ function log {
     echo $(color blue "[-- libcon4m --]" $@)
 }
 
-function meson_init_target {
-    echo ${1} > .meson_last
-    rm deps/local 2>/dev/null
-    ln -s ${PWD}/deps/${OS}-${ARCH} ${PWD}/deps/local
-
-    if [[ ! -d ${1} ]]; then
-        if [[ -f ${1} ]]; then
-            rm -rf ${1}
-        fi
-        log Creating meson target ${1}
-        log meson setup ${@}
-        meson setup ${@}
-    fi
+function ensure_env_setup {
+    export LIBRARY_PATH=${PWD}/deps/${OS}-${ARCH}/:${HOME}/.local/c0/libs/:${HOME}/:
+    log "OS="$(color green ${OS})
+    log "ARCH="$(color green ${ARCH})
+    log "LIBRARY_PATH="$(color green ${LIBRARY_PATH})
 }
 
-function meson_build {
-    meson_init_target ${@}
-    cd ${1}
-
-    log Compiling meson target ${1}
-
-    if [[ ${OS} = "Darwin" ]] ; then
-        meson compile
-        dsymutil c4test
-    else
-        CC=musl-gcc meson compile
-    fi
-
-    CODE=$?
-    if [[ $CODE -eq 0 ]] ; then
-        log "Done!"
-    else
-        log "Build FAILED"
-    fi
-
-    cd ..
-    if [[ ${1} != "debug" ]]; then
-        exit $CODE
-    fi
-
-    if [[ $CODE -ne 0 ]]; then
-        exit $CODE
-    fi
+function cur_exe_loc {
+    echo ${C4M_BUILD_DIR}/${C4M_TEST_EXE}
 }
 
 function meson_hatrack {
@@ -83,7 +56,7 @@ function meson_hatrack {
             rm -rf ${1}
         fi
         log Creating meson target ${1}
-        meson setup ${1}
+        meson setup -Dbuild_hatrack=enable ${1}
     fi
     cd ${1}
 
@@ -113,104 +86,266 @@ function meson_hatrack {
 }
 
 function libcon4m_dev_usage {
-    echo "Usage: ./dev [build | run | release | debug | testbuild | clean]"
+    echo $(color YELLOW "Usage: ./dev [ profile | build | run | debug | rebuild | clean | hash ]")
+    echo $(color CYAN "   profile [arg]") "          Sets the current profile, or shows without arguments."
+    echo "                         Valid profiles are: " $(color blue "dev debug release test")
+    echo $(color CYAN "   build [meson_options]") "  Builds the current profile, passing any additional options to" $(color blue "meson setup") "if provided."
+    echo $(color CYAN "  run") "                    Ensures the current profile is built, and if so, runs the test suite. "
+    echo "                         If not, attempts to compile it first."
+    echo $(color CYAN "  debug") "                  Runs the current profile's test binary in the debugger."
+    echo $(color CYAN " rebuild [meson_options]") "Same as " $(color blue "build") "except it forces a rebuild."
+    echo $(color CYAN " clean [all | profile]") "  Completely wipes the specified profile(s), or the current profile if no argument."
+    echo $(color CYAN " hash") "                   Does a build of libhatrack only."
+
     exit 1
 }
 
-function debug_it {
-    meson_build debug --buildtype=debug
-    DEBUGGER=$(which gdb)
-    DEBUGGER=${DEBUGGER:-$(which lldb)}
-    log "Running debugger:v${DEBUGGER}"
-    ${DEBUGGER} debug/c4test
+function ensure_directory {
+
+    if [[ ! -d ${C4M_BUILD_DIR} ]]; then
+        mkdir ${C4M_BUILD_DIR}
+    fi
+}
+
+function ensure_project {
+    # Return 1 if the project was just setup, 0 if not.
+    meson introspect ${C4M_BUILD_DIR} > /dev/null
+
+    if [[ $? -ne 0 ]] ; then
+        shift
+        log Setting up target: $(color green ${C4M_BUILD_TARGET})
+        meson setup ${C4M_BUILD_DIR} ${C4M_MESON_CONF} ${C4M_PASTHROUGH_ARGS}
+        if [[ $? -ne 0 ]] ; then
+            log Setup for target ${C4M_BUILD_TARGET} $(color FAILED.)
+            exit -1
+        fi
+        log Setup for target ${C4M_BUILD_TARGET}: $(color GREEN SUCCESS)
+    fi
+}
+
+function configure_target {
+    meson configure ${C4M_BUILD_DIR} ${C4M_PASSTHROUGH_ARGS}
+}
+
+function build_target {
+    meson compile ${C4M_BUILD_DIR}
+}
+
+function rebuild_target {
+    meson compile --clean
+}
+
+function set_profile {
+    if [[ $# -eq 0 ]] ; then
+        if [[ -f ${C4M_MESON_STATE_FILE} ]]; then
+            WRITE_TARGET_FILE=0
+            export C4M_BUILD_TARGET=$(cat ${C4M_MESON_STATE_FILE})
+        else
+            WRITE_TARGET_FILE=1
+            export C4M_BUILD_TARGET=dev
+        fi
+    else
+        WRITE_TARGET_FILE=1
+        export C4M_BUILD_TARGET=${1}
+        shift
+        export C4M_PASSTHROUGH_ARGS=${@}
+    fi
+
+
+    case ${C4M_BUILD_TARGET} in
+        dev)
+            export C4M_MESON_CONF="${C4M_DEV_CFG}"
+        ;;
+        debug)
+            export C4M_MESON_CONF="${C4M_DEV_CFG} ${C4M_DEBUG_EXTRA}"
+        ;;
+        release)
+            export C4M_MESON_CONF="${C4M_RELEASE_CFG}"
+        ;;
+        test)
+            export C4M_MESON_CONF="${C4M_TEST_CFG}"
+        ;;
+        *)
+            echo $(color RED "[-- libcon4m --] ") Invalid profile: $(color RED ${C4M_BUILD_TARGET})
+            echo $(color blue "Valid targets are: dev, debug, release, test")
+            return -1
+            ;;
+    esac
+
+    if [[ ${WRITE_TARGET_FILE} -eq 1 ]]; then
+        log "Setting the current profile to:" $(color green ${C4M_BUILD_TARGET})
+        echo ${C4M_BUILD_TARGET} > ${C4M_MESON_STATE_FILE}
+    else
+        log "Current profile is: " $(color YELLOW ${C4M_BUILD_TARGET})
+    fi
+
+    export C4M_BUILD_DIR="build_${C4M_BUILD_TARGET}"
+    log "Current meson build directory is:" $(color YELLOW ${C4M_BUILD_DIR})
+
+    return 0
+
+}
+
+function clean_one_target {
+    TARGET=build_${1}
+    if [[ -d ${TARGET} ]] ; then
+        log Cleaning: ${1}
+        rm -rf ${TARGET}
+    else
+        log Nothing to clean for ${1}
+    fi
+}
+
+function libcon4m_clean {
+    if [[ "$1" == "all" ]] ; then
+        for TARGET in dev debug release test ; do
+            clean_one_target ${TARGET}
+        done
+        if [[ -f ${C4M_MESON_STATE_FILE} ]]; then
+            rm ${C4M_MESON_STATE_FILE}
+        fi
+    else
+        if [[ $# -ne 0 ]]; then
+            for arg in $@ ; do
+                set_profile ${arg}
+                if [[ $? -eq 0 ]] ; then
+                    clean_one_target ${C4M_BUILD_TARGET}
+                fi
+            done
+        else
+            set_profile
+            clean_one_target ${C4M_BUILD_TARGET}
+        fi
+    fi
+}
+
+function libcon4m_set_profile {
+    if [[ $# -gt 1 ]]; then
+        libcon4m_dev_usage
+    fi
+
+    set_profile $@
+
+    if [[ $? -ne 0 ]]; then
+        exit -1
+    fi
+
+    log "Current profile is: " $(cat $C4M_MESON_STATE_FILE)
+
+    ensure_directory
+}
+
+function libcon4m_prebuild {
+    if [[ $# -ne 0 ]]; then
+        case ${1} in
+            dev | debug | release | test)
+                set_profile $@
+                shift
+                ;;
+            *)
+                set_profile
+                export C4M_PASSTHROUGH_ARGS=$@
+                ;;
+        esac
+    else
+        set_profile
+    fi
+
+    ensure_directory
+    ensure_project
+}
+
+function libcon4m_compile {
+    log "Compiling target: " $(color green ${C4M_BUILD_TARGET})
+    which musl-gcc > /dev/null
+
+    if [[ $? -eq 0 ]]; then
+        CC=musl-gcc meson compile -C ${C4M_BUILD_DIR}
+    else
+        meson compile -C ${C4M_BUILD_DIR}
+    fi
+
+
+    if [[ $? -ne 0 ]] ; then
+        log Compilation of target ${C4M_BUILD_TARGET} $(color RED "FAILED.")
+        exit -1
+    fi
+
+    if [[ ${OS} = "Darwin" ]] ; then
+        dsymutil $(cur_exe_loc)
+    fi
 }
 
 function libcon4m_run_tests {
-    shift
+    log Running test exe for target: $(color yellow '[==' $C4M_BUILD_TARGET '==]') in directory: $(color YELLOW ${C4M_BUILD_DIR})
 
-    TARGET=$(cat .meson_last)
-
-    log Running test binary for target: $(color green '[==' $TARGET '==]')
-
-
-    $TARGET/c4test $@
+    $(cur_exe_loc) ${C4M_PASSTHROUGH_ARGS}
     EXIT=$?
     log "Exit status: ${EXIT}"
-    if [[ ${EXIT} -gt 0 ]] && [[ ${EXIT} -lt 128 ]] && [[ $@ == "" ]]  ; then
-        log "Test runner crashed; rerunning tests individually to isolate."
-        HERE=`pwd`
-        cd ../tests
-        for ITEM in `ls basic[0-9]*`; do
-            log Running test: $(color green '[==' $ITEM '==]')
-            ${HERE}/c4test $ITEM
-            if [[ $? -ne 0 ]] ; then
-                echo
-                echo $(color CYAN '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
-                echo $(color CYAN '!! Test case ' $ITEM ' failed !!')
-                echo $(color CYAN '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
-                echo
-            fi
-        done
-        exit 127
+    exit ${EXIT}
+}
+
+function libcon4m_run {
+    libcon4m_prebuild $@
+
+    libcon4m_compile
+
+    set -e
+    libcon4m_run_tests $@
+    CODE=$?
+    if [[ $CODE -eq 0 ]] ; then
+        log "CI/CD tests passed."
+    else
+        log "CI/CD Tests " $(color RED "FAILED.")
+        exit $CODE
     fi
 }
 
-function libcon4m_dev_clean {
-    for item in build debug release cicd; do
-        if [[ -d ${item} ]]; then
-            log Cleaning ${item}
-            cd ${item}
-            meson compile --clean
-            cd ..
-        fi
-    done
+function debug_project {
+    libcon4m_prebuild $@
+    CUR_EXE=$(cur_exe_loc)
 
-    if [[ -f .meson_last ]]; then
-        rm .meson_last
+    libcon4m_compile
+
+
+    DEBUGGER=$(which gdb)
+    DEBUGGER=${DEBUGGER:-$(which lldb)}
+    DEBUGGER=${DEBUGGER:-1}
+
+    if [[ ${DEBUGGER} -eq 1 ]] ; then
+        echo $(color RED ERROR: ) "no debugger found in your path."
+        exit -1
     fi
+    log "Running debugger: ${DEBUGGER} for target:" $(color green '[==' $C4M_BUILD_TARGET '==]')
 
-    log "Done!"
+    ${DEBUGGER} ${CUR_EXE} ${C4M_PASSTHROUGH_ARGS}
 }
 
+ensure_env_setup
 
-if [[ ${#} -eq 0 ]]; then
-    meson_build build
-fi
-
-case $1 in
-    clean)   libcon4m_dev_clean
+case ${1} in
+    clean)   shift
+             libcon4m_clean $@
              ;;
-    build)   meson_build build --buildtype=plain -Duse_memcheck=true
+    build | compile) shift
+             libcon4m_prebuild $@
+             libcon4m_compile
              ;;
-    debug)   meson_init_target debug --buildtype=debug
-             meson configure debug -Duse_memcheck=true
-             meson_build debug
-             debug_it
+    rebuild) shift
+             libcon4m_prebuild $@
+             libcon4m_compile --clean
              ;;
-    testbuild)   meson_init_target cicd --buildtype=debug
-                 meson configure cicd -Duse_memcheck=true
-                 meson_build cicd
-                 ;;
-    sanitizers) meson_init_target sanitizers
-                meson configure sanitizers -Duse_ubsan=true -Duse_asan=true
-                meson build sanitizers
-                ;;
-
-    release) meson_build release --buildtype=release
+    profile) shift
+             libcon4m_set_profile $@
              ;;
-    run)
-             set -e
-             libcon4m_run_tests $@
-             CODE=$?
-             if [[ $CODE -eq 0 ]] ; then
-                 log "CI/CD tests passed."
-             else
-                 log "CI/CD Tests FAILED."
-                 exit $CODE
-             fi
-
+    debug)   shift
+             debug_project $@
              ;;
-    hash)    meson_hatrack hash
+    run)     shift
+             libcon4m_run $@
+             ;;
+    hash)    shift
+             meson_hatrack hash $@
              ;;
     *)
         libcon4m_dev_usage
